# Generated by Django 4.2.30 on 2026-07-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_add_borrowing_is_fine_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Chờ duyệt'), ('BORROWED', 'Đang mượn'), ('RETURNED', 'Đã trả'), ('OVERDUE', 'Quá hạn')], default='BORROWED', max_length=20),
        ),
    ]
